DROP TABLE IF EXISTS player_blocks;
DROP TABLE IF EXISTS ip_blocks;
DROP TABLE IF EXISTS room_log;
DROP TABLE IF EXISTS bets;
DROP TABLE IF EXISTS rounds;
DROP TABLE IF EXISTS action_log;
DROP TABLE IF EXISTS feedbacks;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS room_types;

DROP TYPE IF EXISTS PLAYER_STATUS;
DROP TYPE IF EXISTS BET_OPTION;
DROP TYPE IF EXISTS ACTION;
